### PR TITLE
WIP: Assorted fixups for relative paths

### PR DESCRIPTION
**Pull request by wking**
Details in the commit messages.  With these changes, local testing works fine on most browsers using file:///path/to/_site/index.html.

However, Firefox is more strict about file URIs, so if you want to get Glyphicons working locally you'll need to run a local server (e.g. 'jekyll serve') or [disable `security.fileuri.strict_origin_policy` in `about:config`][1].  More details on the same-origin restrictions [here][2].  We might be able to get this working out of the box on Firefox for file URIs, but I doubt it's worth the trouble.

[1]: http://stackoverflow.com/questions/2856502/css-font-face-not-working-with-firefox-but-working-with-chrome-and-ie
[2]: https://developer.mozilla.org/en-US/docs/Same-origin_policy_for_file:_URIs

### CODE REVIEW

**Comment by wking** [comment]
Don't merge this yet, it still needs doc updates ;).  If the changes look good, I'll work up the doc-update commits and push them into this branch too.

**Comment by gvwilson** [comment]
Thanks for experimenting - moving 'root' into the config and overriding for those pages in the home directory is neat, but if FF won't do the glyphicons w/out changing security settings, I think we're done - I still don't see any way in which this approach is actually simpler or easier than launching a local server.

**Comment by wking** [comment]
Firefox not doing Glyphicons (only for file:// URIs, and then only with the default file URL.strict_origin_policy), is still better than no browser being able to load any assets (including CSS and JavaScript) from file URIs.  And the main benefit to relative links is that "where will I deploy this?" isn't a build-time decision.  For example, you don't need to bump a setting if you rename your repo (and have you.github.io/new_lesson_example > you.github.io/my-lesson).  But if Firefox + file URIs + default security settings is a hard requirement, we can probably shift the font directory and get that working too.  I'll poke around some more.

**Comment by gvwilson** [comment]
Please do - at this point I'm curious about what will actually work.  
Have to be able to preview offline, but other than that... But I'm 
curious: why do you say "better than no browser being able to load any 
assets (including CSS and JavaScript) from file URIs"? I still don't see 
why file URIs is better than having a local server?

**Comment by wking** [comment]
On Sun, May 15, 2016 at 07:02:21AM -0700, Greg Wilson wrote:
> I still don't see why file URIs is better than having a local
> server?

There are two layers here, relative links and working file URIs.  I
think the former is a clear win [1], and we already have it with this
PR as it stands.  I think the latter is also a good thing, because not
needing a local server for testing is one less moving piece.  But it's
less important to me than having relative links.  If we land this PR,
and suggest folks testing on Firefox either use a local server or
disable security.fileuri.strict_origin_policy for testing, that would
be fine with me.  Of course, not having to mention a
Firefox-local-testing caveat would be nice too; whether we land
something to address that probably depends on how cleanly we can work
around Firefox's default security setting.

[1]: https://github.com/gvwilson/new-lesson-example/pull/27#issuecomment-219287164

**Comment by gvwilson** [comment]
I think having variant instructions for one browser or asking authors 
(including first-time contributors) to mess with security settings is a 
cure much (much) worse than the disease.  We'll put this one to a vote - 
let's build our cases in 
https://github.com/gvwilson/new-lesson-example/issues/28

Cheers,

Greg

**Comment by gvwilson** [comment]
We will stick with the current scheme for this rev.

**Pull request closed without merging**
